FROM boyuai/gpu-jupyter
RUN pip install -i https://mirrors.aliyun.com/pypi/simple \
    spacy==2.2.3 \
    tqdm==4.42.0 \
    numpy==1.18.1 \
    scipy==1.4.1 \
    tensorflow==2.1.0 \
    Keras==2.3.1 \
    https://boyuai.oss-cn-shanghai.aliyuncs.com/disk/jupyterhub/misc/en_core_web_sm-2.2.5.tar.gz
