FROM ghcr.io/boyuai/notebook-base-cpp

RUN pip install ipyaliplayer==0.4.1 && jupyter nbextension enable --py --sys-prefix ipyaliplayer
RUN pip install ipyquiz==0.5.6 && jupyter nbextension enable --py --sys-prefix ipyquiz
RUN pip install ipybbycell==0.3.9 && jupyter nbextension enable --py --sys-prefix ipybbycell
