name: Build CPP

on:
  push:
    branches:
      - master
    paths:
      - cpp/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: docker build -t ghcr.io/boyuai/notebook-cpp .
        working-directory: ./cpp
      - name: push
        run: |
          docker push ghcr.io/boyuai/notebook-cpp
