name: Build Base Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          docker build -t ghcr.io/boyuai/notebook-base .
        working-directory: ./base
      - name: push
        run: |
          docker push ghcr.io/boyuai/notebook-base
  build-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          docker build -t ghcr.io/boyuai/notebook-base-cpp -f DockerfileCpp .
        working-directory: ./base
      - name: push
        run: |
          docker push ghcr.io/boyuai/notebook-base-cpp
